version: '3.8'
services:
  chef-workstation:
    image: chef/chefworkstation:latest
    container_name: chef-workstation
    tty: true
    stdin_open: true
    volumes:
      - chef_data:/chef
    environment:
      CHEF_LICENSE: accept
    networks:
      - chef-net

volumes:
  chef_data:

networks:
  chef-net:
    driver: bridge
